//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abeced_Data.Abeced.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AbecedEntity : DbContext
    {
        public AbecedEntity()
            : base("name=AbecedEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Fact> Facts { get; set; }
        public virtual DbSet<FactInfo> FactInfoes { get; set; }
        public virtual DbSet<FactList> FactLists { get; set; }
        public virtual DbSet<LeaderBoard> LeaderBoards { get; set; }
        public virtual DbSet<MainCategory> MainCategories { get; set; }
        public virtual DbSet<QuizSession> QuizSessions { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Revision> Revisions { get; set; }
        public virtual DbSet<Reward> Rewards { get; set; }
        public virtual DbSet<Sharing> Sharings { get; set; }
        public virtual DbSet<StudySession> StudySessions { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
