//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abeced_Data.Abeced.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision
    {
        public int RevisionId { get; set; }
        public string type { get; set; }
        public System.DateTime date { get; set; }
        public bool isCompleted { get; set; }
        public bool isStarted { get; set; }
        public Nullable<bool> isMandatory { get; set; }
        public int userID { get; set; }
        public string sessionIDs { get; set; }
        public int mainSessionID { get; set; }
        public string AbecedUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual User User { get; set; }
    }
}
