//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abeced_Data.Abeced.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reward
    {
        public int RewardId { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public string value { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string img { get; set; }
        public string data { get; set; }
        public int userID { get; set; }
    
        public virtual User User { get; set; }
    }
}
