//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abeced_Data.Abeced.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sharing
    {
        public int ShareId { get; set; }
        public string SenderName { get; set; }
        public string SenderEmail { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string FactList { get; set; }
        public byte[] DateShared { get; set; }
        public string SharedWithIds { get; set; }
        public string SharedWithUserNames { get; set; }
        public string SharedWithEmails { get; set; }
        public string AbecedUserId_Sharer { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
