// <auto-generated />
namespace Abeced.UI.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Lname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lname));
        
        string IMigrationMetadata.Id
        {
            get { return "201803261848503_Lname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
