//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abeced.WebApi.Models.Abeced.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fact()
        {
            this.FactInfoes = new HashSet<FactInfo>();
        }
    
        public int FactId { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
        public string factsheet { get; set; }
        public string qAudio { get; set; }
        public string aAudio { get; set; }
        public string fsAudio { get; set; }
        public string qImage { get; set; }
        public string aImage { get; set; }
        public string points { get; set; }
        public string flashcardRespTime { get; set; }
        public string quizRespTime { get; set; }
        public int courseID { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactInfo> FactInfoes { get; set; }
        public virtual User User { get; set; }
    }
}
