//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abeced.WebApi.Models.Abeced.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactInfo
    {
        public int FactInfoId { get; set; }
        public string numTries { get; set; }
        public string numRight { get; set; }
        public string numWrong { get; set; }
        public string successRate { get; set; }
        public string flashcardRespTime { get; set; }
        public string quizRespTime { get; set; }
        public int factListID { get; set; }
        public int factID { get; set; }
    
        public virtual Fact Fact { get; set; }
        public virtual FactList FactList { get; set; }
    }
}
