//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abeced.WebApi.Models.Abeced.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaderBoard
    {
        public int LeaderBoardId { get; set; }
        public string name { get; set; }
        public string userID { get; set; }
        public string points { get; set; }
    
        public virtual User User { get; set; }
    }
}
