//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abeced.WebApi.Models.Abeced.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizSession
    {
        public int QuizSessionId { get; set; }
        public int UserId { get; set; }
        public string CourseName { get; set; }
        public string FactIds { get; set; }
        public Nullable<double> AveragaScore { get; set; }
        public Nullable<double> PointsEarned { get; set; }
        public byte[] DateSubmitted { get; set; }
        public Nullable<int> Numfacts { get; set; }
        public Nullable<int> NumRevised { get; set; }
    
        public virtual User User { get; set; }
    }
}
